### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by elifoster** [ghuls-apps/github-calendar-api#1]
This is a list of things that are needed for the first release.
- [x] get_total_year

Gets the total number of contributions stated in the little "Total contributions" box below the calendar. Returns an int.
- [x] get_longest_streak

Gets the number of days in the user's longest contribution streak.
- [x] get_current_streak

Gets the number of days in the user's current contribution streak.
- [x] get_weekly

Gets the total number of contributions for each week. Represented through a hash, like so: `{ 0: 15, 1: 3, 2: 18 etc }` The keys are the week numbers (there are roughly 52 weeks in a year), oldest to newest.
- [x] get_daily

Gets the total number of contributions for each week. Represented through a hash, identical to get_weekly except for 365 days rather than 52ish. Oldest to newest.
- [x] get_monthly

Gets the total number of contributions for each month. Represented through a has, like so: `{ 'November': 32, etc }` We may want to use integers instead of names, however, for non-English speakers. This will be more complicated than the rest, as we have to go through each g->day->data-date and check the second integer. 

And just for ease of use:
- [x] get_average_week

Combines the results from get_weekly for an average. This returns an integer representing an average week.
- [x] get_average_day

Combines the results from get_daily for an average. This returns an integer.
- [x] get_average_month

Combines the results from get_monthly for an average. This returns an integer.
